### ISSUE TITLE
Try flakehell for flake8 and black via reviewdog in workflow

### ISSUE THREAD

**Issue by abhishekmishragithub** [predictionmachine/pm-github-actions#42]
- Add [flakehell](https://flakehell.readthedocs.io/) for black and flake8 check via reviewdog in  workflow.
- Using flakehell [config](https://flakehell.readthedocs.io/config.html) we can add configurations for black and flake8 inside single `pyproject.toml` file.

**Comment by tchklovski** [comment]
I was able to get flakehell working by adding:
[tool.flakehell]
# flake8==3.9.0 did not need this, see https://githubmemory.com/repo/flakehell/flakehell/issues/10
extended_default_ignore=[]

to `pyproject.toml`.
would be nice to ditch `setup.cfg`

**Comment by abhishekmishragithub** [comment]
As discussed with @tchklovski, we are dropping flakhell because of following reasons:

1. not maintained,
2. only 222 stars, 
3. does not actually seem to function reliably 
4. All the checks can be done with flake8

We had issues while running flake8 plugins with flakehell.
